{% set version = '2.1.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pastclim
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pastclim_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pastclim/pastclim_{{ version }}.tar.gz
  sha256: 53e15d3dc0f9b61be7ab8ca2d6dc9379b414cb3f597b919d601c01b4ec62ac71

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-curl
    - r-lubridate
    - r-ncdf4
    - r-sf
    - r-terra >=1.7.18
    - r-xml2
  run:
    - r-base
    - r-curl
    - r-lubridate
    - r-ncdf4
    - r-sf
    - r-terra >=1.7.18
    - r-xml2

test:
  commands:
    - $R -e "library('pastclim')"           # [not win]
    - "\"%R%\" -e \"library('pastclim')\""  # [win]

about:
  home: https://evolecolgroup.github.io/pastclim/
  dev_url: https://github.com/EvolEcolGroup/pastclim
  license: CC-BY-4.0
  summary: Methods to easily extract and manipulate palaeoclimate reconstructions for ecological
    and anthropological analyses, as described in Leonardi et al. (2023) <doi:10.1111/ecog.06481>.
  license_family: CC
  license_file:
    - LICENSE.md

extra:
  recipe-maintainers:
    - conda-forge/r
    - dramanica

# Package: pastclim
# Type: Package
# Title: Manipulate Time Series of Palaeoclimate Reconstructions
# Version: 2.1.0
# Authors@R: c( person("Michela", "Leonardi", role = "aut"), person(c("Emily","Y."), "Hallet", role = "ctb"), person("Robert", "Beyer", role = "ctb"), person("Mario", "Krapp", role = "ctb"), person(c("Andrea", "V."), "Pozzi", role = "ctb"), person("Andrea", "Manica", role = c("aut","cre"), email = "am315@cam.ac.uk") )
# Maintainer: Andrea Manica <am315@cam.ac.uk>
# Description: Methods to easily extract and manipulate palaeoclimate reconstructions for ecological and anthropological analyses, as described in Leonardi et al. (2023) <doi:10.1111/ecog.06481>.
# License: CC BY 4.0
# Language: en-GB
# URL: https://github.com/EvolEcolGroup/pastclim, https://evolecolgroup.github.io/pastclim/
# BugReports: https://github.com/EvolEcolGroup/pastclim/issues
# Encoding: UTF-8
# LazyData: true
# LazyDataCompression: xz
# RoxygenNote: 7.3.1
# Depends: R (>= 4.0.0), terra (>= 1.7.18)
# Imports: curl, lubridate, methods, ncdf4, utils, xml2, sf
# Suggests: ggplot2, httr, knitr, rmarkdown, spelling, testthat (>= 3.0.0)
# VignetteBuilder: knitr
# Config/testthat/edition: 3
# NeedsCompilation: no
# Packaged: 2024-06-19 15:11:25 UTC; andrea
# Author: Michela Leonardi [aut], Emily Y. Hallet [ctb], Robert Beyer [ctb], Mario Krapp [ctb], Andrea V. Pozzi [ctb], Andrea Manica [aut, cre]
# Repository: CRAN
# Date/Publication: 2024-06-19 15:40:02 UTC
