{% set version = "2.2.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-pastclim
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pastclim_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pastclim/pastclim_{{ version }}.tar.gz
  sha256: f00765db0d4992ef6372910e3714bac43320978af16e7dc22e193e11caeddc02

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-codetools
    - r-curl
    - r-gstat
    - r-lubridate
    - r-ncdf4
    - r-sf
    - r-terra >=1.7.18
    - r-xml2
    - libgdal-netcdf
  run:
    - r-base
    - r-curl
    - r-gstat
    - r-lubridate
    - r-ncdf4
    - r-sf
    - r-terra >=1.7.18
    - r-xml2
    - libgdal-netcdf

test:
  requires:
    - r-codetools
    - r-testthat
  source_files:
    - tests/
  commands:
    - $R -e "library('pastclim')"                                                     # [not win]
    - $R -e "testthat::test_file('tests/testthat.R', stop_on_failure=TRUE)"           # [not win]
    - "\"%R%\" -e \"library('pastclim')\""                                            # [win]
    - "\"%R%\" -e \"testthat::test_file('tests/testthat.R', stop_on_failure=TRUE)\""  # [win]

about:
  home: https://evolecolgroup.github.io/pastclim/
  dev_url: https://github.com/EvolEcolGroup/pastclim
  license: CC-BY-4.0
  summary: Methods to easily extract and manipulate palaeoclimate reconstructions for ecological and anthropological analyses, as described in Leonardi et al. (2023) <doi:10.1111/ecog.06481>.
  license_family: CC
  license_file:
    - LICENSE.md

extra:
  recipe-maintainers:
    - conda-forge/r
    - dramanica
